# Generated by Django 3.1.5 on 2021-02-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Band_name', models.CharField(max_length=64)),
                ('Genre', models.CharField(choices=[('RO', 'Rock'), ('PU', 'Punk'), ('ME', 'Metal'), ('PO', 'Pop'), ('HH', 'Hip-Hop'), ('ED', 'EDM')], max_length=2)),
                ('Venue', models.CharField(choices=[('BT', 'BoonTunes'), ('ML', 'MeatLocker'), ('BS', 'Backroom Studios'), ('CB', 'Championship Bar'), ('BB', 'Brighton Bar')], max_length=2)),
                ('Requested_date', models.DateField()),
                ('Opening_Acts', models.CharField(max_length=256)),
                ('Ticket_price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Additional_info', models.CharField(max_length=256)),
            ],
        ),
    ]
