# Generated by Django 3.1.7 on 2021-04-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210325_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookashow',
            name='Requested_date',
            field=models.DateTimeField(),
        ),
    ]
