# Generated by Django 3.1.5 on 2021-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210407_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookashow',
            name='Email',
            field=models.CharField(default=1, max_length=320),
            preserve_default=False,
        ),
    ]
